/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:668471df-eb77-421b-ac54-006e97f0b2ad",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eNFe1jcAG",
    "aws_user_pools_web_client_id": "5g1ev4e3g5tihujhgl9kkb69s",
    "oauth": {}
};


export default awsmobile;
